sudo: required
dist: focal

stages:
  - name: Tests
  - name: Push
  - name: Deploy

jobs:
  include:

  - stage: Tests
    name: Docker build Tests

    language: python
    python: "3.8"
  
    services:
      - docker
    before_script: pip install docker-compose
    script:
      - docker-compose run --rm garfieldbot sh -c "python bot.py"
  
  - stage: Push
    script:
      - docker build -t raghavtinker/garfieldbot .
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

      # take image and push to docker hub
      - docker push raghavtinker/garfieldbot