sudo: required
dist: focal
stages:
- name: Tests
- name: Push
- name: Deploy
jobs:
  include:
  - stage: Tests
    name: Docker build Tests
    language: python
    python: '3.8'
    services:
    - docker
    before_script: pip install docker-compose
    script:
    - docker-compose run --rm garfieldbot sh -c "python bot.py"
  - stage: Push
    name: Docker build Push
    script:
    - docker build -t raghavtinker/garfieldbot .
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    - docker push raghavtinker/garfieldbot
  - stage: Deploy
    name: Deploy bot to server
    language: python
    python: '3.8'
    cache: pip
    before_install:
    - openssl aes-256-cbc -K $encrypted_24ae9caab966_key -iv $encrypted_24ae9caab966_iv
      -in nestor.enc -out ./nestor -d
    - chmod 600 nestor
    - ls -la
    install:
    - pip install ansible
    script:
    - ansible-playbook playbooks/deploy.yml
