sudo: required
dist: focal

language: python
python:
  - "3.8"
services:
  - docker

before_script: pip install docker-compose

script:
  - docker-compose run --rm garfieldbot sh -c "python bot.py"

after_success:
  # Log in to docker CLI
  - docker build -t raghavtinker/garfieldbot .
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # Take the image and push them to docker hub 
  - docker push raghavtinker/garfieldbot