---
    - hosts: prod
      tasks:
        - name: Check if repo is cloned
          stat:
            path: "/home/raghav/garfield-bot"
          register: repo_exists
        
        - name: If repo exists then re run docker container
          when: repo_exists.stat.exists
          # first enter folder
          shell: |
            cd /home/raghav/garfield-bot
            git pull

        - name: If repo does not exist clone the repo
          when: not repo_exists.stat.exists
          shell: |
            git clone https://github.com/raghavTinker/garfield-bot.git
        
        # first enter folder
        - name: Enter folder
          when: not repo_exists.stat.exists
          shell: |
            mkdir /home/raghav/garfield-bot/database
            rm -f /home/raghav/garfield-bot/docker-compose.yml
          # copy docker-compose config from home folder and replace the repo compose file
        
        - name: Copy docker-compose config from home folder and replace the repo compose file
          when: not repo_exists.stat.exists
          shell: |
              cp /home/raghav/docker-compose.yml /home/raghav/garfield-bot/
        
        - name: Installing requirements.txt
          when: not repo_exists.stat.exists
          shell: |
              pip3 install -r /home/raghav/garfield-bot/requirements.txt
        
        - name: Running the scraper
          when: not repo_exists.stat.exists
          shell: |
              cd /home/raghav/garfield-bot && python3 scraper.py&
          
          # run docker container
        
        - name: Run docker container
          shell: |
            cd /home/raghav/garfield-bot && docker-compose up -d