---
    - hosts: prod
      tasks:
        - name: Execute Deploy Script
          shell: mkdir -p /home/raghav/garfieldbot
          register: deploy_result
        - debug: msg="{{ deploy_result.stdout }}"