---
    - hosts: prod
      tasks:
        - name: Check if repo is cloned
          stat:
            path: "/home/raghav/garfield-bot"
          register: repo_exists
        
        - name: If repo exists then re run docker container
          when: repo_exists.stat.exists
          # first enter folder
          shell: |
            cd /home/raghav/garfield-bot
            git pull

        - name: If repo does not exist clone the repo
          when: not repo_exists.stat.exists
          git:
            repo:
              - https://github.com/raghavTinker/garfield-bot.git
            dest:
              - /home/raghav/
            clone: yes
            update: yes
        
        # first enter folder
        - name: Enter folder
          shell: |
            cd /home/raghav/garfield-bot
            mkdir database
            rm -f docker-compose.yml
          # copy docker-compose config from home folder and replace the repo compose file
        
        - name: Copy docker-compose config from home folder and replace the repo compose file
          copy:
            src:
              - "/home/raghav/docker-compose.yml"
            dest:
              - "/home/raghav/garfield-bot/docker-compose.yml"
        
        - name: Running the scraper
          shell: |
            - pip3 install -r requirements.txt
            - python3 scraper.py
          
          # run docker container
        
        - name: Run docker container
          shell: |
            cd /home/raghav/garfield-bot
            docker-compose up -d